"""Autogenerate

Revision ID: 86751ff1f0f6
Revises: f54a2830844f
Create Date: 2022-07-05 17:25:24.037470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86751ff1f0f6'
down_revision = 'f54a2830844f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'votes')
    # ### end Alembic commands ###
