"""Autogenerate

Revision ID: 98b3cad9cbbb
Revises: 86751ff1f0f6
Create Date: 2022-07-05 17:25:41.574868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b3cad9cbbb'
down_revision = '86751ff1f0f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
