"""Autogenerate

Revision ID: b32ffb1ac476
Revises: 98b3cad9cbbb
Create Date: 2022-07-05 17:26:45.055808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32ffb1ac476'
down_revision = '98b3cad9cbbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
