"""Autogenerate

Revision ID: f54a2830844f
Revises: c6a184f77050
Create Date: 2022-07-05 17:24:53.603264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54a2830844f'
down_revision = 'c6a184f77050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
